name: Publish

on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Publish webextension
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Build
              run: |
                  npm ci
                  npm run build
            - name: Upload & release
              uses: mnao305/chrome-extension-upload@3.0.0
              with:
                  file-path: releases/*.zip
                  glob: true
                  extension-id: ${{ secrets.EXTENSION_ID }}
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
